// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgZEiEYFgqu3lp04I0dFtLu85t0KHXfAQ',
    appId: '1:491566413232:web:6c7a07e3850e503dbad275',
    messagingSenderId: '491566413232',
    projectId: 'homeserviceapp-809aa',
    authDomain: 'homeserviceapp-809aa.firebaseapp.com',
    storageBucket: 'homeserviceapp-809aa.firebasestorage.app',
    measurementId: 'G-BD1W3LGEZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDk39pRydA_5oemuPzFYxvLYbcirToym0',
    appId: '1:491566413232:android:f5d194cfa1533949bad275',
    messagingSenderId: '491566413232',
    projectId: 'homeserviceapp-809aa',
    storageBucket: 'homeserviceapp-809aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8opG9Qrw6YSppEJbbBu_GFwqG6ZoiFw',
    appId: '1:491566413232:ios:3362cfa20c5994bbbad275',
    messagingSenderId: '491566413232',
    projectId: 'homeserviceapp-809aa',
    storageBucket: 'homeserviceapp-809aa.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8opG9Qrw6YSppEJbbBu_GFwqG6ZoiFw',
    appId: '1:491566413232:ios:3362cfa20c5994bbbad275',
    messagingSenderId: '491566413232',
    projectId: 'homeserviceapp-809aa',
    storageBucket: 'homeserviceapp-809aa.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgZEiEYFgqu3lp04I0dFtLu85t0KHXfAQ',
    appId: '1:491566413232:web:8351f146fb2a04b6bad275',
    messagingSenderId: '491566413232',
    projectId: 'homeserviceapp-809aa',
    authDomain: 'homeserviceapp-809aa.firebaseapp.com',
    storageBucket: 'homeserviceapp-809aa.firebasestorage.app',
    measurementId: 'G-Z7KMPG01GE',
  );

}